### ISSUE TITLE
Add support for SDK 29 devices (Android 10)

### ISSUE THREAD

**Issue by pamartineza** [bitrise-steplib/steps-virtual-device-testing-for-android#60]
Currently, if we add the existing Firebase TestLab device that supports SDK 29, the Pixel 4, step fails with error:

Starting test run failed, error: failed to start test: 406, error: Invalid device configuration: device (Pixel4) not found. Available devices: [Nexus10 Nexus4 Nexus5 Nexus5X Nexus6 Nexus6P Nexus7 Nexus7_clone_16_9 Nexus9 NexusLowRes NexusLowRes_Q NexusTabletLowRes2 NexusTabletLowRes3 Pixel2 Pixel2_Q]

**Comment by ahvth-bitrise** [comment]
The issue here is that the Pixel 4 is not one of the supported virtual devices in Firebase Test Lab. The error message includes the list of Devices that you are able to use in this case: Nexus10 Nexus4 Nexus5 Nexus5X Nexus6 Nexus6P Nexus7 Nexus7_clone_16_9 Nexus9 NexusLowRes NexusLowRes_Q NexusTabletLowRes2 NexusTabletLowRes3 Pixel2 Pixel2_Q

**Comment by pamartineza** [comment]
@ahvth-bitrise Right, I just realized that I had to look for "virtual devices" not "actual" ones on Firebase Test Lab website. Using Pixel 2 I can properly pass tests on SDK 29.

Thanks
