### ISSUE TITLE
Retry mechanism looks broken

### ISSUE THREAD

**Issue by glureau-betclic** [bitrise-steplib/steps-virtual-device-testing-for-android#63]
When using retry on a flaky test suite, I expect to have the test (or test suite) to be re-run on this device until it's OK or it reaches the max retry attempt. If the retry is OK, then the build on Bitrise should be green too.

What I observed is that if 1 device fails to run my tests, it will be asked to rerun it but doesn't take into account the result, so it will re-run until the max retry attempt, and the result is build failed.

![image](https://user-images.githubusercontent.com/35920611/74222200-3aa5f380-4cb4-11ea-8675-e3ba0435e2b4.png)

Previous discussion on the retry mechanism: 
https://github.com/bitrise-steplib/steps-virtual-device-testing-for-android/issues/39
https://discuss.bitrise.io/t/retry-mechanism-on-tasks/8456

**Comment by JoeMaher** [comment]
Seeing the same issue, any update on this?

<img width="1082" alt="Screen Shot 2020-03-19 at 12 38 55 pm" src="https://user-images.githubusercontent.com/4361354/77026150-adef0380-69de-11ea-9606-01ab737fe0a1.png">

**Comment by non-binary** [comment]
Hi @glureau-betclic @JoeMaher 

The `Number of times a test execution is reattempted` input of the step sets the `--num-flaky-test-attempts` flag of the test run, based on the docs: https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run .

`Specifies the number of times a test execution should be reattempted if one or more of its test cases fail for any reason. An execution that initially fails but succeeds on any reattempt is reported as FLAKY.
The maximum number of reruns allowed is 10. (Default: 0, which implies no reruns.) All additional attempts are executed in parallel.`

So this flag is not like a retry (which re-runs the step in case of failure and after the first successful run marks it as successful), it supposed to prove that the test case is flaky (this can be done by re-running the test case as many times as defined via the flag so that you can see: 5 run failed out of 10 runs, so this case if flaky).

Please don't hesitate to follow-up if you have any other questions.

Kind regards,
Luna

**Comment by JoeMaher** [comment]
Can the wording be altered then? It is very misleading.

> Specifies the number of times a test execution should be reattempted if one or more of its test cases fail for any reason. An execution that initially fails but succeeds on any reattempt is reported as FLAKY.

Where does it get marked as flaky?

**Comment by non-binary** [comment]
@JoeMaher This is Google's documentation not ours. Please read through their documentation for more information. Thanks!

**Comment by DanielJette** [comment]
I agree that the documentation should be improved on the workflow step. Currently it says:

> Specifies the number of times a test execution should be reattempted if one or more of its test cases fail for any reason. An execution that initially fails but succeeds on any reattempt is reported as FLAKY.
> The maximum number of reruns allowed is 10. (Default: 0, which implies no reruns.)

This should include the `All additional attempts are executed in parallel`.

But, for me, the most important change we can make here is that I was expecting the stage to pass if the test passed on any of the retries. It seems incorrect to me to fail the step if a test is flaky. Flaky means that it passed at least once, so I think that it should not mark the step as failed.
