### ISSUE TITLE
false, true, false

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-steplib/steps-virtual-device-testing-for-android#9]
![image](https://user-images.githubusercontent.com/1173057/34052846-229f74a8-e192-11e7-980f-45da9dac86b5.png)

**Comment by viktorbenei** [comment]
Thanks @bootstraponline we'll check this ASAP! ;)

**Comment by viktorbenei** [comment]
Not to dev team: I think this might be because:

- either because the input's value is not string (`true`/`false` instead of `"true"`/`"false"`)
- or an issue in the Workflow Editor
- or the two at the same time (the editor should be able to handle this even if the value is not string, but the value definitely should be string ;) )

**Comment by trapacska** [comment]
Hey @bootstraponline !

Thank you for reporting the issue, it is now resolved in the new version of the step: 🎉🚀

https://github.com/bitrise-steplib/steps-virtual-device-testing-for-android/releases/tag/1.0.0
